### ISSUE TITLE
点击打不开

### ISSUE THREAD

**Issue by ilaipi** [swenyang/react-date-picker#1]
版本是`1.1.5`

代码：
```
               <DatePicker ref="picker" type="date" locale="zh-cn"
                  defaultDate="Sat Jul 30 2016 18:17:37 GMT+0800 (CST)"
                  onOpen={date => console.log('onOpen:', date)}
                  onClose={date => console.log('onClose:', date)}
                  onConfirm={date => console.log('onConfirm:', date)}
                  onCancel={date => console.log('onCancel:', date)}
                ></DatePicker>
```

按钮是能出来，点的时候 `onOpen` 和 `onClose` 轮着调用。
还有什么是必须的设置啊？看例子里没有任何参数都能工作...

**Comment by swenyang** [comment]
把你的代码放到`Example.js`是可以工作的。打不开是什么症状？有报错么

**Comment by ilaipi** [comment]
没有报错诶，如果不加onOpen 和 onClose的两个`console`，症状就是没有任何反应，选择框不弹出来

**Comment by ilaipi** [comment]
我找到[另一个库](https://github.com/lanjingling0510/react-mobile-datepicker) 手机上能打开，我试了一下感觉滑动效果不好，每次滑动最多滚动5年。
你这个库好像滑动效果很好

**Comment by swenyang** [comment]
`on*`事件不是必需的，加不加都行。你可以把你的源代码上传到github仓库看看。

**Comment by ilaipi** [comment]
我是用的`react-weui`，这个`<DatePicker>`放在`<CellBody>`里面。

我看了看`Example.js`，没看出来是怎么触发`open`的，能大概说下吗？
