### ISSUE TITLE
Error on npm install, babel-eslint

### ISSUE THREAD

**Issue by netpoetica** [swenyang/react-date-picker#2]
After cloning, I run npm install and get:

```
Cannot find module 'babel-eslint'
Error: Cannot find module 'babel-eslint'
```

Here are my versions:

➜  react-date-picker git:(master) ✗ node -v
v6.10.3
➜  react-date-picker git:(master) ✗ npm -v
3.10.10

I think babel-eslint is just missing from the package.json

**Comment by swenyang** [comment]
Thanks! Just added the missing `babel-eslint` to package.json.
